# Container for building the environment
#FROM condaforge/mambaforge:4.9.2-5 as conda
#FROM continuumio/miniconda3

FROM ubuntu:20.04
ENV PATH="/root/miniconda3/bin:${PATH}"
#ENV PATH="/root/miniconda3/Library/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update

RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh

# touch the download (see https://github.com/conda/conda/issues/9948)
#RUN find /root/miniconda3/ -type f -exec touch {} +

# update
#RUN apt-get update

# get dependencies that don't seem to be installing via mamba
#RUN apt-get install -y libsm6 libxext6 libxrender-dev

# Grab requirements.txt.
ADD ./hls_nrt_environment.yml /tmp/environment.yml

# Add our code and set working directory
ADD . /opt/webapp/
WORKDIR /opt/webapp

RUN conda env create -p /env --file /tmp/environment.yml && \
  conda clean -afy && \
  conda init

# added after getting error during rasterio import
#RUN export LD_PRELOAD=/env/lib/python3.10/site-packages/rasterio/../../../libgdal.so.30
#RUN unset LD_LIBRARY_PATH

#EXPOSE 8080

#CMD ["/env/bin/panel", "serve", "hls_gcloud_app.ipynb", "--port", "8080", "--num-procs", "4", "--allow-websocket-origin", "*"]

CMD ["/env/bin/panel", "serve", "hls_gcloud_app.ipynb", "--address", "0.0.0.0", "--port", "8080", "--allow-websocket-origin", "*"]
